use fantasy_football;

delete from t_positions;

insert into t_position (description, createdAt, updatedAt) values ("QB",now(),now());
insert into t_position (description, createdAt, updatedAt) values ("RB",now(),now());
insert into t_position (description, createdAt, updatedAt) values ("WR",now(),now());
insert into t_position (description, createdAt, updatedAt) values ("TE",now(),now());
insert into t_position (description, createdAt, updatedAt) values ("LB",now(),now());
insert into t_position (description, createdAt, updatedAt) values ("S",now(),now());
insert into t_position (description, createdAt, updatedAt) values ("C",now(),now());
insert into t_position (description, createdAt, updatedAt) values ("DL",now(),now());
insert into t_position (description, createdAt, updatedAt) values ("K",now(),now());

delete from t_nfl_teams;

insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Bills","Buffalo",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Dolphins","Miami",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Patriots","New England",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Jets","New York",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Ravens","Baltimore",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Bengals","Cincinnati",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Browns","Cleveland",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Steelers","Pittsburgh",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Texans","Houston",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Colts","Indianapolis",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Jaguars","Jacksonville",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Titans","Tennessee",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Broncos","Denver",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Chiefs","Kansas City",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Raiders","Oakland",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Chargers","San Diego",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Cowboys","Dallas",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Giants","New York",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Eagles","Philadelphia",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Redskins","Washington",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Bears","Chicago",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Lions","Detroit",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Packers","Green Bay",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Vikings","Minnesota",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Falcons","Atlanta",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Panthers","Carolina",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Saints","New Orleans",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Buccaneers","Tampa Bay",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Cardinals","Arizona",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Rams","St. Louis",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("49ers ","San Francisco",now(),now());
insert into t_nfl_teams (description, city, createdAt, updatedAt) values ("Seahawks","Seattle",now(),now());

insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2017,2018,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2018,2019,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2019,2020,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2020,2021,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2021,2022,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2022,2023,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2023,2024,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2024,2025,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2025,2026,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2026,2027,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2027,2028,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2028,2029,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2029,2030,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2030,2031,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2031,2032,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2032,2033,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2033,2034,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2034,2035,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2035,2036,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2036,2037,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2037,2038,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2038,2039,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2039,2040,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2040,2041,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2041,2042,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2042,2043,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2043,2044,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2044,2045,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2045,2046,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2046,2047,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2047,2048,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2048,2049,now(),now());
insert into t_seasons (start_year, end_year, createdAt, updatedAt) values(2049,2050,now(),now());

delete from t_players;

insert into t_players(fname,lname,position,nfl_team,jersey_number, createdAt, updatedAt) values ("mike","jones",1,"lions",34,now(),now());
insert into t_players(fname,lname,position,nfl_team,jersey_number, createdAt, updatedAt) values ("john","johnson",2,"cowboys",65,now(),now());
insert into t_players(fname,lname,position,nfl_team,jersey_number, createdAt, updatedAt) values ("steve","jirjis",3,"giants",23,now(),now());
insert into t_players(fname,lname,position,nfl_team,jersey_number, createdAt, updatedAt) values ("josh","khao",4,"jets",5,now(),now());
insert into t_players(fname,lname,position,nfl_team,jersey_number, createdAt, updatedAt) values ("joe","mama",5,"broncos",13,now(),now());

delete from t_fantasy_teams;

insert into t_fantasy_teams (description, createdAt, updatedAt) values ("steven fantasy team",now(),now());
insert into t_fantasy_teams (description, createdAt, updatedAt) values ("josh fantasy team",now(),now());
insert into t_fantasy_teams (description, createdAt, updatedAt) values ("purple fantasy team",now(),now());
insert into t_fantasy_teams (description, createdAt, updatedAt) values ("ft winner fantasy team",now(),now());
insert into t_fantasy_teams (description, createdAt, updatedAt) values ("nfl beast fantasy team",now(),now());

delete from tx_fantasy_team_rosters;

insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,1,1,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,2,1,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,3,1,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,4,null,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,5,null,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,6,1,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,7,1,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,8,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,9,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,10,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,11,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,12,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,13,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,14,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,15,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,16,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, fantasy_team_id, createdAt, updatedAt) values(1,1,17,2,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, createdAt, updatedAt) values(1,1,18,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, createdAt, updatedAt) values(1,1,19,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, createdAt, updatedAt) values(1,1,20,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, createdAt, updatedAt) values(1,1,21,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, createdAt, updatedAt) values(1,1,22,now(),now());
insert into tx_fantasy_team_rosters (season_id, week_id, player_id, createdAt, updatedAt) values(1,1,23,now(),now());

delete from t_game_stats;

insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,1,1,12,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,1,1,34,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,1,1,32,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,1,1,45,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,2,1,6,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,2,1,4,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,2,1,32,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,3,2,67,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,3,2,65,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,3,2,34,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,1,3,2,56,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,1,1,87,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,1,1,5,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,1,1,69,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,1,1,87,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,2,1,2,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,2,1,54,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,2,1,7,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,3,2,24,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,3,2,65,now(),now());
insert into t_game_stats (season_id, week_id, player_id, fantasy_team_id,  players_game_fantasy_score, createdAt, updatedAt) values (1,2,3,2,97,now(),now());

delete from t_game_schedules;

insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",1,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",2,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",3,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",4,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",5,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",6,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",7,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",8,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",9,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",10,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",11,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",12,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",13,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",14,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",15,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (1,"NFL",16,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",1,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",2,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",3,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",4,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",5,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",6,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",7,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",8,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",9,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",10,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",11,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",12,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",13,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",14,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",15,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (2,"NFL",16,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",1,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",2,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",3,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",4,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",5,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",6,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",7,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",8,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",9,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",10,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",11,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",12,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",13,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",14,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",15,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (3,"NFL",16,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",1,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",2,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",3,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",4,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",5,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",6,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",7,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",8,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",9,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",10,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",11,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",12,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",13,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",14,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",15,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (4,"NFL",16,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",1,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",2,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",3,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",4,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",5,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",6,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",7,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",8,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",9,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",10,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",11,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",12,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",13,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",14,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",15,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (5,"NFL",16,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",1,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",2,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",3,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",4,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",5,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",6,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",7,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",8,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",9,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",10,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",11,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",12,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",13,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",14,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",15,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (6,"NFL",16,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",1,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",2,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",3,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",4,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",5,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",6,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",7,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",8,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",9,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",10,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",11,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",12,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",13,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",14,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",15,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (7,"NFL",16,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",1,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",2,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",3,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",4,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",5,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",6,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",7,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",8,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",9,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",10,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",11,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",12,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",13,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",14,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",15,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (8,"NFL",16,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",1,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",2,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",3,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",4,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",5,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",6,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",7,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",8,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",9,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",10,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",11,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",12,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",13,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",14,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",15,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (9,"NFL",16,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",1,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",2,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",3,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",4,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",5,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",6,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",7,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",8,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",9,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",10,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",11,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",12,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",13,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",14,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",15,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (10,"NFL",16,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",1,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",2,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",3,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",4,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",5,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",6,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",7,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",8,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",9,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",10,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",11,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",12,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",13,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",14,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",15,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (11,"NFL",16,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",1,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",2,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",3,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",4,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",5,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",6,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",7,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",8,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",9,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",10,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",11,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",12,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",13,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",14,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",15,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (12,"NFL",16,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",1,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",2,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",3,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",4,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",5,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",6,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",7,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",8,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",9,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",10,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",11,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",12,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",13,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",14,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",15,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (13,"NFL",16,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",1,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",2,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",3,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",4,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",5,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",6,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",7,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",8,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",9,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",10,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",11,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",12,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",13,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",14,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",15,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (14,"NFL",16,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",1,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",2,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",3,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",4,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",5,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",6,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",7,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",8,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",9,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",10,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",11,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",12,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",13,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",14,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",15,17,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (15,"NFL",16,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",1,18,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",2,19,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",3,20,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",4,21,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",5,22,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",6,23,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",7,24,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",8,25,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",9,26,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",10,27,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",11,28,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",12,29,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",13,30,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",14,31,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",15,32,now(),now());
insert into t_game_schedules (week_id,game_type,home_team,away_team, createdAt, updatedAt)values (16,"NFL",16,17,now(),now());
